### ISSUE TITLE
Variome cofe installation problem

### ISSUE THREAD

**Issue by lodexhosreposy2** [Cafe-Variome/CafeVariome#12]
Hello, 

I'm working on setting up a healthcare application for data sharing.
Your Cafe Variome application fits the bill perfectly. I'd like to know how
do I need a valid key to install Cafe Variome?

Thanks in advance

**Comment by rini21** [comment]
Hey, please let us know your Base URL so that we can generate an installation key for you. Kindly get in touch with Prof. Anthony Brookes at ajb97@leicester.ac.uk to discuss your application needs and customised support for your project.
